### ISSUE TITLE
Multiple issues when applying on a complex antlr file

### ISSUE THREAD

**Issue by goodwanghan** [amykyta3/speedy-antlr-tool#12]
Hello Alex,

First of all, thank you so much for creating such a tool. I am the creator of [Fugue](https://github.com/fugue-project/fugue). Fugue has its own DSL called Fugue SQL which is a higher level language on top of standard SQL. We are using antlr4 to create the language parser. It works great, but it is slow. That is why I am looking for alternative solutions that can be faster. You tool seems exactly what I need.

I created an experimental [repo](https://github.com/goodwanghan/fugue-sql-antlr) and added you to access it. There are a couple of issues

1. `+=` the list operator in antlr will create private members ([example](https://github.com/goodwanghan/fugue-sql-antlr/blob/c6cb9bb10d5ad9d6a79c57fef2bfb1ba657f069e/fugue_sql.g4#L676)), I think it is almost useless, but it is causing issues because C++ target does not have that, so the tool will throw exceptions. Currently, I have a simple [workaround](https://github.com/goodwanghan/fugue-sql-antlr/blob/c6cb9bb10d5ad9d6a79c57fef2bfb1ba657f069e/scripts/sa_wrapper.py#L8-L17).
2. It can't reach parity with python target. This may be fine, but the problem is I find the result not deterministic. You can run [this test](https://github.com/goodwanghan/fugue-sql-antlr/blob/c6cb9bb10d5ad9d6a79c57fef2bfb1ba657f069e/tests/test_equivalent.py#L7) and there are a few issues:
  * It seems EOF is handled differently (minor issue)
  * After fixing the EOF issue, If you run the test multiple times, you will find it has different errors, sometimes `stop` not found, sometimes `parentCtx` not found. I think this is the major issue I need your help.

To reproduce, you can clone the repo.

To rebuild the SQL
```bash
make sql
```

To install locally:
```bash
pip install -e .
```

To run the test
```bash
pytest tests/test_equivalent.py
```

If you run the test step multiple steps, you could see different error messages. (You may need to fix the EOF handling issue first to see various other issues)

Thanks!

**Comment by kentrutan** [comment]
I implemented code to handle the ANTLR "list label" mentioned in item 1 above. It works on our Modelica grammar, but I think it needs some refactoring and more testing before submitting. I won't be able to get to it this month. @amykyta3 would you like me to submit a WIP PR in the meantime or just wait to submit the finished code in June?

**Comment by goodwanghan** [comment]
Thanks @kentrutan

Actually, I think I fixed these problems + 4.10.1 upgrade in this PR https://github.com/amykyta3/speedy-antlr-tool/pull/13 and I also verified them with a lot of unit tests, they align with the python version. @amykyta3 and @kentrutan can you take a look at the PR? I tried to minimize the code change.

**Comment by kentrutan** [comment]
@goodwanghan you said you had a workaround, so I thought you just ignored the list labels.

Can you point me to where your code builds the Python version of the C++ lists of rules?

**Comment by goodwanghan** [comment]
The main problem of (1) is fixed by https://github.com/amykyta3/speedy-antlr-tool/pull/13/files#diff-13d88b41ddfa4b4b3ecec5205bafe8b5f605ab532bec95b19090246213c00281R56

There are already member functions handling the list, the problem is that private members `_***` are generated in the python antlr code, so the tool also tries to link the private members with the C++ implementations, which will fail. So I just make sure the tool doesn't touch private members.

Here is a sample generated code:

```python
    class DescribeColNameContext(ParserRuleContext):

        def __init__(self, parser, parent:ParserRuleContext=None, invokingState:int=-1):
            super().__init__(parent, invokingState)
            self.parser = parser
            self._identifier = None # IdentifierContext
            self.nameParts = list() # of IdentifierContexts

        def identifier(self, i:int=None):
            if i is None:
                return self.getTypedRuleContexts(fugue_sqlParser.IdentifierContext)
            else:
                return self.getTypedRuleContext(fugue_sqlParser.IdentifierContext,I)
```

so the member function `identifier(i)` can get the ith element of the list. But `self._identifier` is created in the constructor. So the tool is confused in this case. We just avoid doing anything for `_identifier`, then the problem is solved.

**Comment by kentrutan** [comment]
OK I see now. Thanks for explaining! I'll give your changes a try, but probably won't be able to get to it until next month.

You might want to consider rebasing your PR into maybe 2 commits, one for the list label fix and one for the start/stop stuff, with each commit having a good title and description about what it does (like what you did above). That would have helped me tremendously and would make it easier for @amykyta3 to merge your changes with less work (assuming he would clean up the commits). You'll have to force push your history rewites into your fork.

**Comment by kentrutan** [comment]
@goodwanghan For your example code above, the expected behavior of ANTLR list labels is that the `DescribeColNameContext` attribute `nameParts` should be a list of `IdentifierContext` objects. When I test your code on my example, the list label attributes do not exist. Do you agree that `nameParts` does not exist when you test your example?

**Comment by amykyta3** [comment]
PR has been merged. Thanks!
