### ISSUE TITLE
Include option for `#undef` for Windows

### ISSUE THREAD

**Issue by svengiegerich** [amykyta3/speedy-antlr-tool#16]
Within the package [pytsql](https://github.com/Quantco/pytsql/pull/73#discussion_r1147241481), we encountered an [issue](https://github.com/Quantco/pytsql/actions/runs/4466632088/jobs/7856926164?pr=73) when using `speedy-antlr-tool` on Windows: 
👉 conflicting (uppercase) verbs with Window specific macro's.

Luckily the fix was relatively easy, at least in our case: adding `#undef`(see [#undef](https://learn.microsoft.com/en-us/windows/win32/menurc/-undef)) to the auto-generated `*Lexer.h`.

**Comment by amykyta3** [comment]
I'm not sure i understand what the specific request or issue is.

If there is an issue with the auto-generated `*Lexer.h` file, that is not created by this tool. Those files are generated by ANTLR, whose issue page can be found here: https://github.com/antlr/antlr4/issues
