### ISSUE TITLE
Fatal Error C1061 on parsing sa_*_cpp_parser.cpp file

### ISSUE THREAD

**Issue by m-zakeri** [amykyta3/speedy-antlr-tool#7]
If there are many rules in the input grammar the if-the-else statements lead to Fatal Error C1061 on parsing sa_*_cpp_parser.cpp file.
It seems that the C++ compiler can not compiler more than 128 nested blocks!
[https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1061?view=msvc-160](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1061?view=msvc-160)

**Comment by m-zakeri** [comment]
For example, I have trouble to build a Java9.g4 parser with the current version of Speedy ANTLR.

**Comment by amykyta3** [comment]
Ha! What a strange limitation.
Is this also an issue for Linux targets using the GCC compiler?

I guess it wouldn't be too hard to add a workaround that breaks the if/else apart in this case

**Comment by m-zakeri** [comment]
I did not try other C++ compilers such as GCC or Clang. For simplicity, I removed some rules from the if-else body especially the lexical rules which are not required for parsing. However, it is not a permanent solution.

**Comment by amykyta3** [comment]
Agree that's not a good permanent solution.
I'll see what I can do about improving this function to use a proper lookup table rather than a long if/else.

**Comment by amykyta3** [comment]
Finally got around to this one!
Fixed in v1.3.0
