### ISSUE TITLE
Compiler error when buiding cpp parser backaend  

### ISSUE THREAD

**Issue by m-zakeri** [amykyta3/speedy-antlr-tool#9]
Hello everyone,
I get the following error when trying to run `python setup install` to build a CPP backend parser for my grammar.

```
sa_javalabeled_cpp_parser.cpp(91): error C2440: '=': cannot convert from 'antlrcpp::Any' to 'PyObject *'
sa_javalabeled_cpp_parser.cpp(91): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```

The error points to the following lines in sa_javalabeled_cpp_parser.cpp file:

```
  // Translate Parse tree to Python
        SA_JavaLabeledTranslator visitor(&translator);
        result = visitor.visit(parse_tree);

```

I use the latest version of speedy-antlr and antlr and python 3.8.x  and MVC++14 on windows 10.

**Comment by amykyta3** [comment]
Fixed in v1.2.0
